// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDb4kjpDXVbMytfhFibERMPIiUgxvuC5o',
    appId: '1:366343536705:web:1d3132cdeca1aa85e006c0',
    messagingSenderId: '366343536705',
    projectId: 'memoir-b4ce2',
    authDomain: 'memoir-b4ce2.firebaseapp.com',
    storageBucket: 'memoir-b4ce2.appspot.com',
    measurementId: 'G-9YGYYDJE48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFoYVUZ0b-rtrGststOg1_lkUi3ziwB6U',
    appId: '1:366343536705:android:8adbe4e9d5d00c61e006c0',
    messagingSenderId: '366343536705',
    projectId: 'memoir-b4ce2',
    storageBucket: 'memoir-b4ce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ycZ4mZGaw3seaOHrOel3CfYRPRCotC8',
    appId: '1:366343536705:ios:0f7579d7c95ec2b5e006c0',
    messagingSenderId: '366343536705',
    projectId: 'memoir-b4ce2',
    storageBucket: 'memoir-b4ce2.appspot.com',
    iosBundleId: 'com.example.memoir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ycZ4mZGaw3seaOHrOel3CfYRPRCotC8',
    appId: '1:366343536705:ios:9c65f78896216922e006c0',
    messagingSenderId: '366343536705',
    projectId: 'memoir-b4ce2',
    storageBucket: 'memoir-b4ce2.appspot.com',
    iosBundleId: 'com.example.memoir.RunnerTests',
  );
}
