// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-lsTHwBGIJUPvVRU7YHRZjteuErRNU5k',
    appId: '1:243577572654:web:b723788bcc8f169d97febf',
    messagingSenderId: '243577572654',
    projectId: 'coffeeshop-df780',
    authDomain: 'coffeeshop-df780.firebaseapp.com',
    storageBucket: 'coffeeshop-df780.appspot.com',
    measurementId: 'G-B10TTT19VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF96z58LugkFcagX4j6Kkotqd4b5usFsw',
    appId: '1:243577572654:android:5b709ed6cf7b4e1c97febf',
    messagingSenderId: '243577572654',
    projectId: 'coffeeshop-df780',
    storageBucket: 'coffeeshop-df780.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3R99lzgfnVBh7HyZD5R_pfBlzi-eRATQ',
    appId: '1:243577572654:ios:7cbbc9d9672adb3797febf',
    messagingSenderId: '243577572654',
    projectId: 'coffeeshop-df780',
    storageBucket: 'coffeeshop-df780.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3R99lzgfnVBh7HyZD5R_pfBlzi-eRATQ',
    appId: '1:243577572654:ios:7378d5df3f00e03b97febf',
    messagingSenderId: '243577572654',
    projectId: 'coffeeshop-df780',
    storageBucket: 'coffeeshop-df780.appspot.com',
    iosBundleId: 'com.example.coffeeShop.RunnerTests',
  );
}
