// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyNub4ovVuSRw3wUipghMDcIfctWEEqaU',
    appId: '1:4513938450:web:fa0b7177bc881f81b06ccb',
    messagingSenderId: '4513938450',
    projectId: 'neuro-sentry',
    authDomain: 'neuro-sentry.firebaseapp.com',
    storageBucket: 'neuro-sentry.appspot.com',
    measurementId: 'G-96VHZG9QSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JU1d36CDHlnf-9YSoEahNO5AD9dPiqI',
    appId: '1:4513938450:android:81f0581443c80ef7b06ccb',
    messagingSenderId: '4513938450',
    projectId: 'neuro-sentry',
    storageBucket: 'neuro-sentry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdALsqls2wHs6kOBgZBGg4ATrL700wYoQ',
    appId: '1:4513938450:ios:e0014c00f28bb473b06ccb',
    messagingSenderId: '4513938450',
    projectId: 'neuro-sentry',
    storageBucket: 'neuro-sentry.appspot.com',
    iosBundleId: 'com.example.mentalHealthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdALsqls2wHs6kOBgZBGg4ATrL700wYoQ',
    appId: '1:4513938450:ios:dcd052269dde1a02b06ccb',
    messagingSenderId: '4513938450',
    projectId: 'neuro-sentry',
    storageBucket: 'neuro-sentry.appspot.com',
    iosBundleId: 'com.example.mentalHealthapp.RunnerTests',
  );
}
