// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwpY1AhJwBUNsKS9iRsflssV6gk-M-HOk',
    appId: '1:846938609983:web:d5d44bb5137dd658129b8a',
    messagingSenderId: '846938609983',
    projectId: 'lostget-faafe',
    authDomain: 'lostget-faafe.firebaseapp.com',
    storageBucket: 'lostget-faafe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8TsPvMTINZb6H4Eca3tckJsdyL8XM8uU',
    appId: '1:846938609983:android:cc61872bfe52dc93129b8a',
    messagingSenderId: '846938609983',
    projectId: 'lostget-faafe',
    storageBucket: 'lostget-faafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5h3S91tkAofigZs-PfSTtDLQeZxVv_UI',
    appId: '1:846938609983:ios:dc8448e3b098b20d129b8a',
    messagingSenderId: '846938609983',
    projectId: 'lostget-faafe',
    storageBucket: 'lostget-faafe.appspot.com',
    iosClientId: '846938609983-tcs2m16i2r7r5v3dua9b7lvj8agun2ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.responsiveAdminDashboard',
  );
}
