// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ehv2m_vBM73nMSoe38j27T-0vfVw6ww',
    appId: '1:474733292748:web:7a2e91f3e3e9d5bb862669',
    messagingSenderId: '474733292748',
    projectId: 'dailycommutte',
    authDomain: 'dailycommutte.firebaseapp.com',
    storageBucket: 'dailycommutte.appspot.com',
    measurementId: 'G-SNLNHWRPLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8OW83tX5dWYVulX3vl6xV_cpLzhUUtc',
    appId: '1:474733292748:android:a65141089e5111dc862669',
    messagingSenderId: '474733292748',
    projectId: 'dailycommutte',
    storageBucket: 'dailycommutte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsz3-cJbG7D47HQ_rI0JUg37xSqWgRyLc',
    appId: '1:474733292748:ios:1f8dfdaadcc814d1862669',
    messagingSenderId: '474733292748',
    projectId: 'dailycommutte',
    storageBucket: 'dailycommutte.appspot.com',
    iosBundleId: 'com.example.appMessengerModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsz3-cJbG7D47HQ_rI0JUg37xSqWgRyLc',
    appId: '1:474733292748:ios:f54ce8c975a96b12862669',
    messagingSenderId: '474733292748',
    projectId: 'dailycommutte',
    storageBucket: 'dailycommutte.appspot.com',
    iosBundleId: 'com.example.appMessengerModule.RunnerTests',
  );
}
